#!/usr/make -f
# Author: Eraldo P Marinho
# First version: Wed Oct 10 14:47:20 -03 2018
# Makefile for main directory of the MyPas project
#

projectname=mypas

default:

clean:

mostlyclean: clean
	$(RM) *.tmp *~
